# Generated by Django 6.1 on 2026-08-10 09:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_number_per_business',
        ),
        migrations.RemoveConstraint(
            model_name='quote',
            name='unique_quote_number_per_business',
        ),
        migrations.RemoveConstraint(
            model_name='receipt',
            name='unique_receipt_number_per_business',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='email_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_due_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='next_receipt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='payment_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pdf_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='quotation_validity_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='receipt_prefix',
            field=models.CharField(default='REC', max_length=30),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='tax_name',
            field=models.CharField(blank=True, default='GST', max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=30),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='quotation_prefix',
            field=models.CharField(default='QUO', max_length=30),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(default='My Business', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='api.payment'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'invoice_number'], name='api_invoice_busines_3c94f3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'status'], name='api_invoice_busines_ef284b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['business', 'due_date'], name='api_invoice_busines_495d35_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'status'], name='api_payment_busines_72979b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='api_payment_invoice_af9f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['business', 'quote_number'], name='api_quote_busines_8ca5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['business', 'status'], name='api_quote_busines_9aced2_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['business', 'receipt_number'], name='api_receipt_busines_c53236_idx'),
        ),
    ]
