# Generated by Django 6.1 on 2026-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appsettings_email_from_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='invoice_template',
            field=models.CharField(default='template1', max_length=50),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='quotation_template',
            field=models.CharField(default='template1', max_length=50),
        ),
    ]
