# Generated by Django 6.1 on 2026-08-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_ticketmessage_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('category', models.CharField(choices=[('goods', 'Goods & Materials'), ('services', 'Services & Consulting'), ('raw_materials', 'Raw Materials'), ('logistics', 'Logistics & Shipping'), ('utilities', 'Utilities & Rent'), ('it_software', 'IT & Software'), ('contractor', 'Contractor & Freelance'), ('equipment', 'Machinery & Equipment'), ('other', 'Other')], default='goods', max_length=50)),
                ('tax_number', models.CharField(blank=True, default='', max_length=100)),
                ('pan_number', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=50)),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_terms', models.CharField(blank=True, default='Net 30', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='api.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'category'], name='api_vendor_busines_725fb9_idx'), models.Index(fields=['business', 'is_active'], name='api_vendor_busines_a3b847_idx')],
            },
        ),
    ]
