# Generated by Django 6.1 on 2026-08-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('temp_data', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'otp'], name='api_signupv_email_696f46_idx'), models.Index(fields=['email', 'expires_at'], name='api_signupv_email_5c386b_idx')],
            },
        ),
    ]
