# Generated by Django 6.1 on 2026-08-29 04:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vendor_user_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.CharField(default='v1.0', max_length=20)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='deliverables/files/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('admin_review', 'Under Admin Review'), ('revision_required', 'Revision Required'), ('admin_approved', 'Admin Approved'), ('client_review', 'Under Client Review'), ('client_changes_requested', 'Client Changes Requested'), ('client_approved', 'Client Approved'), ('completed', 'Completed')], default='submitted', max_length=40)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('client_notes', models.TextField(blank=True, default='')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='api.businessprofile')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_deliverables', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='api.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverableApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], max_length=20)),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected / Revision Required'), ('request_changes', 'Changes Requested')], max_length=30)),
                ('feedback', models.TextField(blank=True, default='')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.deliverable')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('approved', 'Approved'), ('client_review', 'Client Review'), ('client_approved', 'Client Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.businessprofile')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='api.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.project'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='Assigned Vendor', max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.project')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='api.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'vendor')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_vendors',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', through='api.ProjectMember', to='api.vendor'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(default='Professional', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='active', max_length=30)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('49.00'), max_digits=10)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('max_projects', models.PositiveIntegerField(default=50)),
                ('max_users', models.PositiveIntegerField(default=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('assigned_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='api.vendor')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('access_level', models.CharField(choices=[('admin_only', 'Admin Only'), ('project_members', 'Project Members & Vendor'), ('client_visible', 'Client & Project Members'), ('public_tenant', 'All Tenant Users')], default='project_members', max_length=30)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.businessprofile')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.vendor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliverable',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='api.task'),
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_role', models.CharField(default='admin', max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tasks/comments/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.task')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=100)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='api_auditlo_busines_8b74c0_idx'), models.Index(fields=['action'], name='api_auditlo_action_0a1743_idx'), models.Index(fields=['entity_type', 'entity_id'], name='api_auditlo_entity__ad4253_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_type', models.CharField(choices=[('direct_admin_vendor', 'Admin <-> Vendor'), ('direct_admin_client', 'Admin <-> Client'), ('project_room', 'Project Team Room')], default='direct_admin_vendor', max_length=40)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.businessprofile')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.project')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['business', 'conversation_type'], name='api_message_busines_ecea71_idx'), models.Index(fields=['sender', 'is_read'], name='api_message_sender__c47869_idx'), models.Index(fields=['recipient', 'is_read'], name='api_message_recipie_eb753b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['business', 'status'], name='api_project_busines_d4e517_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'status'], name='api_project_client__752d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='api_task_project_9ce1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_vendor', 'status'], name='api_task_assigne_19f9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['business', 'status'], name='api_task_busines_e2f335_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['business', 'access_level'], name='api_documen_busines_e90128_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project'], name='api_documen_project_87a109_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['project', 'status'], name='api_deliver_project_8302ba_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['vendor', 'status'], name='api_deliver_vendor__712bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['business', 'status'], name='api_deliver_busines_d6736e_idx'),
        ),
    ]
