# Generated by Django 6.1 on 2026-08-29 06:06

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_businessprofile_is_active_businessprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='max_projects',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='max_users',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='FREE_TRIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIAL_ACTIVE', 'Trial Active'), ('TRIAL_EXHAUSTED', 'Trial Exhausted'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='TRIAL_ACTIVE', max_length=30),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['business', 'status'], name='api_subscri_busines_d85938_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan_name', 'status'], name='api_subscri_plan_na_57fa86_idx'),
        ),
    ]
