# Generated by Django 6.1 on 2026-08-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_subscription_trial_ended_at_subscription_trial_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(default='Enterprise Multi-Tenant SaaS Platform', max_length=255)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('favicon_url', models.CharField(blank=True, default='', max_length=500)),
                ('support_email', models.EmailField(default='support@system.io', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='+1 800 555 0199', max_length=50)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('default_timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('platform_description', models.TextField(blank=True, default='Comprehensive multi-tenant business and project workspace management.')),
                ('trial_enabled', models.BooleanField(default=True)),
                ('trial_limit', models.PositiveIntegerField(default=5)),
                ('trial_type', models.CharField(default='PROJECTS', max_length=50)),
                ('action_after_limit', models.CharField(default='REQUIRE_UPGRADE', max_length=50)),
                ('plans_config', models.JSONField(blank=True, default=dict)),
                ('platform_payment_gateway', models.CharField(default='Razorpay / Stripe', max_length=100)),
                ('merchant_account_status', models.CharField(default='Connected & Active', max_length=100)),
                ('settlement_status', models.CharField(default='Operational', max_length=100)),
                ('billing_currency', models.CharField(default='USD', max_length=10)),
                ('webhook_status', models.CharField(default='Live (200 OK)', max_length=100)),
                ('smtp_provider', models.CharField(default='SendGrid / Custom SMTP', max_length=100)),
                ('smtp_host', models.CharField(default='smtp.sendgrid.net', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(default='apikey', max_length=255)),
                ('from_email', models.EmailField(default='no-reply@system.io', max_length=254)),
                ('from_name', models.CharField(default='Platform System Notifications', max_length=255)),
                ('smtp_encryption', models.CharField(default='TLS', max_length=20)),
                ('notification_events', models.JSONField(blank=True, default=dict)),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('require_special_char', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=120)),
                ('login_attempt_limit', models.PositiveIntegerField(default=5)),
                ('invitation_expiry_days', models.PositiveIntegerField(default=7)),
                ('enforce_mfa', models.BooleanField(default=False)),
                ('default_business_currency', models.CharField(default='USD', max_length=10)),
                ('default_business_timezone', models.CharField(default='UTC', max_length=100)),
                ('default_business_plan', models.CharField(default='FREE_TRIAL', max_length=50)),
                ('default_business_status', models.CharField(default='active', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
